### ISSUE TITLE
Inconsistent readout

### ISSUE THREAD

**Issue by jhrdinka** [HEP-FCC/FCCSW#247]
The readout is inconsistent within the current detector. E.g. the lengths of our system IDs differ in the Calorimeters and the Tracker (for example see: https://github.com/HEP-FCC/FCCSW/blob/master/Detector/DetFCChhHCalTile/compact/FCChh_HCalBarrel_TileCal.xml#L56, https://github.com/HEP-FCC/FCCSW/blob/master/Detector/DetFCChhTrackerTkLayout/compact/Tracker.xml#L9). This leads to inconsistencies in the volumeIDs. 
In order to avoid these problems in the future we should agree on the lengths of the subsystems and define them in the master, similar to how it is done here: https://github.com/iLCSoft/lcgeo/blob/master/CLIC/compact/CLIC_o3_v13/CLIC_o3_v13.xml#L188 .

**Comment by zaborowska** [comment]
Hi Julia,

we have an agreement on the length of the 'system'. It is 4 bits and if tracker uses more it is only to accommodate more systems which as I remember was required by acts (@vvolkl - true?).
'system' is always the first one in the bitfield so it uses the lowest bits in the ID. Therefore, identification of the system is made using the lowest 4 bits. So any system can use more if that is really necessary as long as the lowest 4 bits contain correct system ID (defined [here](https://github.com/HEP-FCC/FCCSW/blob/master/Detector/DetFCChhBaseline1/compact/FCChh_DectDimensions.xml#L94)).

**Comment by vvolkl** [comment]
Hi @jhrdinka,

Anna is completely correct. We chose this readout at the time only to be consistent with the globals we agreed on, and still be able to use the dd4hep plugin. The idea was that even if you read out the "system" field of the volumeID with 4 bit length, you will still get the correct id (as there is just an offset of 2^5), at least for the inner and outer tracker ( the forward tracker wasn't supported by the dd4hep plugin at the time, so I'm not sure this is true there ). Maybe we were trying to be a bit too clever with this workaround - what exactly are the inconsistencies you see? It will be good to have a discussion on this, because in my understanding the best solution would be to just be able to use one `detector` tag for both endcap and have the positive / negative distinction at the next lower DetElement hierarchy - this would also help with the slow startup of FCCSW when using the tracker! But I don't know how complicated this is, it didn't seem possible at the time.

**Comment by jhrdinka** [comment]
Thank you for your answers. Yesterday I was in the dd4hep meeting, because I have still a problem with my volumeIDs. They told me, that it is a problem if the Calorimeters and the Tracker use different bit length of the system ID and this could probably solve my problem. However I can understand how it was done. I am in contact with them to check, whether this is really a problem and I think I will write a little test for that.
@vvolkl we can have a separate discussion on that. As long as the sensitive detector elements of the endcaps are unique this should be possible.

**Comment by MarkusFrankATcernch** [comment]
@vvolkl, @zaborowska : 
Theoretically the argument is correct. 
However, there are numerous computations in particular when it comes to the handling of volume ids, where the bitfield values are accessed using the IDDDescriptor object. At the end of the day the bitfield computations are done using integers for values and masks and here things could go unex[ectedly wrong.
I for sure would not bet my life, that e.g. the VolumeManager still works correctly using these assumptions.

In order to stay consistent, it is highly advisable to have a common length of the system ID and then add a second field (ie. barrel, endcap-A, endcap-B, etc) if a subdivision of a given subdetector is necessary.
This also would lead to a clean solution without having to rely on hacks with assumptions, which later have a potential of becoming a bomb.

**Comment by jhrdinka** [comment]
Actually I think it would be really useful to have the bitfield divided further. So that there is one mask giving you the different whole detector systems (e.g. Tracker, ECal, HCal, Muon, Chamber) and then another mask giving you the different volumes of these detectors.

**Comment by MarkusFrankATcernch** [comment]
@vvolkl, @zaborowska : 
Theoretically the argument is correct. 
However, there are numerous computations in particular when it comes to the handling of volume ids, where the bitfield values are accessed using the IDDDescriptor object. At the end of the day the bitfield computations are done using integers for values and masks and here things could go unex[ectedly wrong.
I for sure would not bet my life, that e.g. the VolumeManager still works correctly using these assumptions.

In order to stay consistent, it is highly advisable to have a common length of the system ID and then add a second field (ie. barrel, endcap-A, endcap-B, etc) if a subdivision of a given subdetector is necessary.
This also would lead to a clean solution without having to rely on hacks with assumptions, which later have a potential of becoming a bomb.
